#!/bin/bash

# For use on EmuELEC ONLY!!!!!

LAYOUT_PARTITIONS_COUNT="@LAYOUT_PARTITIONS_COUNT@"

# Suggested: system. Recorded examples: CE_SYSTEM
LAYOUT_PARTITION_SYSTEM_NAME="@LAYOUT_PARTITION_SYSTEM_NAME@"
# Suggested: 512M for CE, 2G for EE
LAYOUT_PARTITION_SYSTEM_SIZE="@LAYOUT_PARTITION_SYSTEM_SIZE@"
# Suggested: SYSTEM. Recorded examples: CE_SYSTEM
LAYOUT_PARTITION_SYSTEM_LABEL="@LAYOUT_PARTITION_SYSTEM_LABEL@"


# Suggested: storage. Recorded examples: CE_STORAGE
LAYOUT_PARTITION_STORAGE_NAME="@LAYOUT_PARTITION_STORAGE_NAME@"
# Suggested: 
LAYOUT_PARTITION_STORAGE_SIZE="@LAYOUT_PARTITION_STORAGE_SIZE@"
# Suggested: STORAGE. Recorded examples: CE_STORAGE
LAYOUT_PARTITION_STORAGE_LABEL="@LAYOUT_PARTITION_STORAGE_LABEL@"


# Suggested: roms
LAYOUT_PARTITION_ROMS_NAME="@LAYOUT_PARTITION_ROMS_NAME@"
LAYOUT_PARTITION_ROMS_SIZE="@LAYOUT_PARTITION_ROMS_SIZE@"

LAYOUT_PARTITION_ROMS_LABEL="@LAYOUT_PARTITION_ROMS_LABEL@"

. /etc/aminstall.conf